



stages:
  - upload_private_registry
  - upload_docker_hub

variables:
  HBASE_VERSION: 2.6.1
  DOCKER_HUB_USERNAME: $DOCKER_HUB_USERNAME
  DOCKER_HUB_PASSWORD: $DOCKER_HUB_PASSWORD

build_hbase_distributed_docker_image:
  stage: upload_private_registry
  tags:
    - docker-build
  script:
    - cd hbase-distributed
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg HBASE_VERSION=$HBASE_VERSION -t registry.gitlab.com/massflows/devops/hbase-docker/hbase-distributed:$HBASE_VERSION .
    - docker push $CI_REGISTRY/massflows/devops/hbase-docker/hbase-distributed:$HBASE_VERSION


build_hbase_standalone_docker_image:
  stage: upload_private_registry
  tags:
    - docker-build
  script:
    - cd hbase-standalone
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --build-arg HBASE_VERSION=$HBASE_VERSION -t registry.gitlab.com/massflows/devops/hbase-docker/hbase-standalone:$HBASE_VERSION .
    - docker push $CI_REGISTRY/massflows/devops/hbase-docker/hbase-standalone:$HBASE_VERSION

dockerhub_distributed:
  stage: upload_docker_hub
  tags:
    - docker-build
  script:
    - cd hbase-distributed
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD docker.io
    - docker build --build-arg HBASE_VERSION=$HBASE_VERSION -t docker.io/jannickkappelmann/hbase-distributed:$HBASE_VERSION .
    - docker push docker.io/jannickkappelmann/hbase-distributed:$HBASE_VERSION

dockerhub_standalone:
  stage: upload_docker_hub
  tags:
    - docker-build
  script:
    - cd hbase-standalone
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD docker.io
    - docker build --build-arg HBASE_VERSION=$HBASE_VERSION -t docker.io/jannickkappelmann/hbase-standalone:$HBASE_VERSION .
    - docker push docker.io/jannickkappelmann/hbase-standalone:$HBASE_VERSION



