version: '3'

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1.5G
    ports:
      - 9870:9870
      - 9000:9000
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
  hbase-master:
    depends_on:
      - zookeeper
      - datanode
      - namenode
    image: hbase-distributed:2.6.1
    environment:
      SERVICE_PRECONDITION: "namenode:9000 datanode:9864"
    command: master
    ports:
      - 16000:16000
      - 16010:16010
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 500M
  hbase-regionserver:
    depends_on:
      - hbase-master
      - datanode
      - namenode
      - zookeeper
    image: hbase-distributed:2.6.1
    environment:
      SERVICE_PRECONDITION: "hbase-master:16010"
    command: regionserver
    ports:
      - 16030:16030
      - 16201:16201
      - 16301:16301
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 1G

  hbase-stargate:
    depends_on:
      - hbase-master
    image: hbase-distributed:2.6.1
    command: stargate
    ports:
      - 8080:8080
      - 8085:8085

  zookeeper:
    image: harisekhon/zookeeper:latest
    ports:
      - 2181:2181

volumes:
  datanode:
  namenode:
  
networks:
  default:
    name: hbase-network
